### ISSUE TITLE
NVM_AUTO_USE used incorrectly according to documentation.

### ISSUE THREAD

**Issue by kirangadhave** [crivotz/dot_files#1]
https://github.com/crivotz/dot_files/blob/658ef79453faef7bf5cc11c6150423f7fcd77565/linux/zplugin/zshrc#L81

Hey i was using your ZSH config as an inspiration for setting up my own. I came across the above plugin you use zsh-nvm.

You are using NVM_AUTO_USE=true after loading the plugin.
The documentation for the plugin states that we should be setting the env variable before loading the plugin as mentioned [here](https://github.com/lukechilds/zsh-nvm#auto-use)

Just thought I'd let you know. 

PS: I havent tested it in the way you have set it up.

**Comment by crivotz** [comment]
Thanks mate, my fault ;)
