### ISSUE TITLE
ZSH autocompletion for aliases doesn't work.

### ISSUE THREAD

**Issue by niyumard** [crivotz/dot_files#2]
Hi!
I'm using your zshrc and I've set an alias for [todo.sh](https://github.com/todotxt/todo.txt-cli).

Autocompletion for options works perfectly for the todo.sh itself but doesn't work for the alias, it just lists files and directories.
Is there any chance you'd fix autosuggestions for aliases?

**Comment by crivotz** [comment]
I should have fixed it in the last commit by removing the `setopt complete_aliases`

I tested it with the following code
```
# todo
zinit ice as"completion"; zinit snippet https://github.com/todotxt/todo.txt-cli/blob/master/todo_completion
zinit ice lucid wait"0" as"program" from"gh-r" mv"todo*/todo.sh -> todo.sh" atload"alias todo='todo.sh'"
zinit light "todotxt/todo.txt-cli"
```

Let me know if I can close the issue ;)

**Comment by niyumard** [comment]
It works perfectly! I can't thank you enough. Thank you!

**Comment by crivotz** [comment]
> It works perfectly! I can't thank you enough. Thank you!

you are welcome 😃
